### ISSUE TITLE
缺少依赖包

### ISSUE THREAD

**Issue by orangeyts** [FinVolution/das#2]
com.microsoft.sqlserver:mssql-jdbc:jar:6.2.2.jre7.ctrip is missing
com.oracle:ojdbc6:jar:11.2.0.4 is missing

这两个包，需要自己安装一下么？

**Comment by hejiehui** [comment]
DAS底层使用了修改过的携程DAL核心，数据库驱动依赖后面会加到文档目录。目前先从这里安装吧：https://github.com/ctripcorp/dal/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF-%E9%9B%86%E6%88%90%E8%AF%B4%E6%98%8E

**Comment by ShengyuanLu** [comment]
> 
> 
> DAS底层使用了修改过的携程DAL核心，数据库驱动依赖后面会加到文档目录。目前先从这里安装吧：https://github.com/ctripcorp/dal/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF-%E9%9B%86%E6%88%90%E8%AF%B4%E6%98%8E

@orangeyts 
已添加驱动依赖安装下载和说明：[安装驱动依赖](https://github.com/ppdaicorp/das/wiki/DasClient-%E9%9B%86%E6%88%90%E8%AF%B4%E6%98%8E#bulb-%E5%AE%89%E8%A3%85%E9%A9%B1%E5%8A%A8%E4%BE%9D%E8%B5%96)
