### ISSUE TITLE
本地代码运行连接报错

### ISSUE THREAD

**Issue by SoftwareKing** [FinVolution/das#4]
![image](https://user-images.githubusercontent.com/6858857/69049009-d3bcc980-0a39-11ea-96f2-80abe3c4edc9.png)

**Comment by ShengyuanLu** [comment]
已在[DasConsole 安装启动](https://github.com/ppdaicorp/das/wiki/DasConsole-%E5%AE%89%E8%A3%85%E5%90%AF%E5%8A%A8)中添加安装数据库的步骤。
